### ISSUE TITLE
how to add new music

### ISSUE THREAD

**Issue by x0arthur** [DARKDEV22/PMV_Maker#2]
hi bro I wanna the way to add any new music and generate music templates in txt. thanks

**Comment by DARKDEV22** [comment]
**Download latest version** [here](https://github.com/DARKDEV22/PMV_Maker/releases/download/pmv-2/pmv-maker2.rar)
then you can add .txt file timestamp template folder (recomend timestamp you get from capcat - the second that is part of videos has), and add .mp3 file in music folder with same name as the timestamp for example rickRoll.txt with rickRoll.mp3
